import { Product, Order, User, AnalyticsData } from './types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Classic Denim Jacket',
    description: 'Timeless denim jacket with modern fit. Perfect for layering in any season.',
    price: 129.99,
    category: 'Jackets',
    image: 'https://images.unsplash.com/photo-1634136912882-61fd36144a3a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwamFja2V0JTIwY2FzdWFsfGVufDF8fHx8MTc2MjI0NTE0NXww&ixlib=rb-4.1.0&q=80&w=1080',
    images: [
      'https://images.unsplash.com/photo-1634136912882-61fd36144a3a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwamFja2V0JTIwY2FzdWFsfGVufDF8fHx8MTc2MjI0NTE0NXww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Blue', 'Black', 'Grey'],
    inStock: true,
    isCustomizable: false,
    rating: 4.5,
    reviews: 128,
  },
  {
    id: '2',
    name: 'Premium Cotton Shirt',
    description: 'High-quality cotton shirt with custom embroidery option. Tailored fit for modern gentleman.',
    price: 79.99,
    category: 'Shirts',
    image: 'https://images.unsplash.com/photo-1661802365632-bb2b2f68eb51?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwc2hpcnQlMjBmYXNoaW9ufGVufDF8fHx8MTc2MjI0NTE0NXww&ixlib=rb-4.1.0&q=80&w=1080',
    images: [
      'https://images.unsplash.com/photo-1661802365632-bb2b2f68eb51?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwc2hpcnQlMjBmYXNoaW9ufGVufDF8fHx8MTc2MjI0NTE0NXww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White', 'Black', 'Navy', 'Grey'],
    inStock: true,
    isCustomizable: true,
    customizationOptions: [
      {
        id: 'monogram',
        name: 'Monogram Initials',
        type: 'text',
        price: 15,
      },
      {
        id: 'thread',
        name: 'Thread Color',
        type: 'select',
        options: ['Gold', 'Silver', 'Black', 'Navy'],
        price: 0,
      },
    ],
    rating: 4.8,
    reviews: 95,
  },
  {
    id: '3',
    name: 'Designer Sneakers',
    description: 'Comfortable and stylish sneakers for everyday wear. Premium materials and craftsmanship.',
    price: 149.99,
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1624006389438-c03488175975?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwc25lYWtlcnMlMjBzaG9lc3xlbnwxfHx8fDE3NjIxNzE4OTR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    images: [
      'https://images.unsplash.com/photo-1624006389438-c03488175975?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwc25lYWtlcnMlMjBzaG9lc3xlbnwxfHx8fDE3NjIxNzE4OTR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['White', 'Black', 'Grey'],
    inStock: true,
    isCustomizable: false,
    rating: 4.6,
    reviews: 203,
  },
  {
    id: '4',
    name: 'Luxury Watch',
    description: 'Elegant timepiece with Swiss movement. Can be engraved for personal touch.',
    price: 399.99,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1706892807280-f8648dda29ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwYWNjZXNzb3JpZXMlMjB3YXRjaHxlbnwxfHx8fDE3NjIxNzUwNjZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    images: [
      'https://images.unsplash.com/photo-1706892807280-f8648dda29ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwYWNjZXNzb3JpZXMlMjB3YXRjaHxlbnwxfHx8fDE3NjIxNzUwNjZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    sizes: ['One Size'],
    colors: ['Silver', 'Gold', 'Black'],
    inStock: true,
    isCustomizable: true,
    customizationOptions: [
      {
        id: 'engraving',
        name: 'Back Engraving',
        type: 'text',
        price: 25,
      },
    ],
    rating: 4.9,
    reviews: 156,
  },
  {
    id: '5',
    name: 'Slim Fit Trousers',
    description: 'Modern slim fit trousers with stretch fabric. Perfect for office or casual wear.',
    price: 89.99,
    category: 'Pants',
    image: 'https://images.unsplash.com/photo-1541840031508-326b77c9a17e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwcGFudHMlMjB0cm91c2Vyc3xlbnwxfHx8fDE3NjIyNDUxNDd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    images: [
      'https://images.unsplash.com/photo-1541840031508-326b77c9a17e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwcGFudHMlMjB0cm91c2Vyc3xlbnwxfHx8fDE3NjIyNDUxNDd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    sizes: ['28', '30', '32', '34', '36', '38'],
    colors: ['Black', 'Navy', 'Grey', 'Khaki'],
    inStock: true,
    isCustomizable: false,
    rating: 4.4,
    reviews: 87,
  },
  {
    id: '6',
    name: 'Casual Polo Shirt',
    description: 'Classic polo shirt in premium pique cotton. Versatile and comfortable.',
    price: 59.99,
    category: 'Shirts',
    image: 'https://images.unsplash.com/photo-1641736755184-67380b9a002c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwZmFzaGlvbiUyMG1vZGVsfGVufDF8fHx8MTc2MjIzODI1Nnww&ixlib=rb-4.1.0&q=80&w=1080',
    images: [
      'https://images.unsplash.com/photo-1641736755184-67380b9a002c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwZmFzaGlvbiUyMG1vZGVsfGVufDF8fHx8MTc2MjIzODI1Nnww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black', 'Navy', 'Red'],
    inStock: true,
    isCustomizable: true,
    customizationOptions: [
      {
        id: 'logo',
        name: 'Custom Logo Position',
        type: 'select',
        options: ['Chest Left', 'Chest Right', 'Back'],
        price: 20,
      },
    ],
    rating: 4.3,
    reviews: 64,
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    userId: 'user-1',
    items: [
      {
        product: mockProducts[0],
        quantity: 1,
        size: 'L',
        color: 'Blue',
      },
    ],
    total: 129.99,
    status: 'delivered',
    paymentStatus: 'paid',
    paymentMethod: 'Credit Card',
    shippingAddress: {
      fullName: 'John Doe',
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
      phone: '+1 234 567 8900',
    },
    createdAt: '2024-10-15T10:30:00Z',
    updatedAt: '2024-10-20T14:30:00Z',
  },
  {
    id: 'ORD-002',
    userId: 'user-1',
    items: [
      {
        product: mockProducts[1],
        quantity: 2,
        size: 'M',
        color: 'White',
        customization: {
          monogram: 'JD',
          thread: 'Gold',
        },
      },
    ],
    total: 189.98,
    status: 'shipped',
    paymentStatus: 'paid',
    paymentMethod: 'PayPal',
    shippingAddress: {
      fullName: 'John Doe',
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
      phone: '+1 234 567 8900',
    },
    createdAt: '2024-11-01T09:15:00Z',
    updatedAt: '2024-11-03T11:20:00Z',
  },
];

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'john.doe@example.com',
    name: 'John Doe',
    role: 'customer',
    addresses: [
      {
        fullName: 'John Doe',
        street: '123 Main St',
        city: 'New York',
        state: 'NY',
        zipCode: '10001',
        country: 'USA',
        phone: '+1 234 567 8900',
      },
    ],
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'admin-1',
    email: 'admin@fashionbrand.com',
    name: 'Admin User',
    role: 'admin',
    addresses: [],
    createdAt: '2023-01-01T00:00:00Z',
  },
];

export const mockAnalytics: AnalyticsData = {
  totalRevenue: 45234.56,
  totalOrders: 324,
  totalCustomers: 1247,
  totalProducts: 156,
  revenueByMonth: [
    { month: 'Jan', revenue: 3200 },
    { month: 'Feb', revenue: 3800 },
    { month: 'Mar', revenue: 4200 },
    { month: 'Apr', revenue: 3900 },
    { month: 'May', revenue: 4500 },
    { month: 'Jun', revenue: 5100 },
    { month: 'Jul', revenue: 4800 },
    { month: 'Aug', revenue: 5300 },
    { month: 'Sep', revenue: 4700 },
    { month: 'Oct', revenue: 5400 },
    { month: 'Nov', revenue: 5835 },
  ],
  topProducts: [
    { product: mockProducts[1], sales: 234 },
    { product: mockProducts[2], sales: 198 },
    { product: mockProducts[0], sales: 176 },
    { product: mockProducts[3], sales: 145 },
    { product: mockProducts[4], sales: 132 },
  ],
  ordersByStatus: [
    { status: 'Delivered', count: 245 },
    { status: 'Shipped', count: 43 },
    { status: 'Processing', count: 28 },
    { status: 'Pending', count: 8 },
  ],
};
