import { Product, Order, Review, Coupon } from '../types';

export const mockProducts: Product[] = [
  // T-Shirts
  {
    id: '1',
    name: 'Essential Cotton T-Shirt',
    slug: 'essential-cotton-tshirt',
    description: 'Premium 100% cotton t-shirt with a relaxed fit. Soft, breathable, and perfect for everyday wear.',
    price: 29.99,
    salePrice: 24.99,
    category: 'T-Shirts',
    subcategory: 'Basic Tees',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Navy', 'Gray'],
    materials: ['100% Cotton'],
    stock: 150,
    rating: 4.7,
    reviewCount: 234,
    featured: true,
    newArrival: false,
    bestseller: true,
    tags: ['basic', 't-shirt', 'cotton', 'casual'],
    sku: 'TS-001',
    productType: 'simple' as const,
  },
  {
    id: '2',
    name: 'Premium Graphic T-Shirt',
    slug: 'premium-graphic-tshirt',
    description: 'Modern graphic tee with bold design. Made from soft cotton blend for ultimate comfort.',
    price: 34.99,
    category: 'T-Shirts',
    subcategory: 'Graphic Tees',
    images: [
      'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800',
      'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Olive'],
    materials: ['Cotton Blend'],
    stock: 95,
    rating: 4.5,
    reviewCount: 156,
    featured: true,
    newArrival: true,
    bestseller: false,
    tags: ['graphic', 't-shirt', 'design'],
    sku: 'TS-002',
    productType: 'simple' as const,
  },
  {
    id: '3',
    name: 'Vintage Wash T-Shirt',
    slug: 'vintage-wash-tshirt',
    description: 'Soft vintage-washed t-shirt with a lived-in feel. Perfect for a relaxed, casual look.',
    price: 32.99,
    category: 'T-Shirts',
    subcategory: 'Vintage Tees',
    images: [
      'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=800',
      'https://images.unsplash.com/photo-1622445275463-afa2ab738c34?w=800',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Charcoal', 'Rust', 'Navy'],
    materials: ['Cotton'],
    stock: 68,
    rating: 4.8,
    reviewCount: 189,
    featured: false,
    newArrival: true,
    bestseller: false,
    tags: ['vintage', 't-shirt', 'casual'],
    sku: 'TS-003'
  },
  {
    id: '4',
    name: 'Striped Crew Neck T-Shirt',
    slug: 'striped-crew-neck-tshirt',
    description: 'Classic striped crew neck t-shirt. Timeless design meets modern comfort.',
    price: 36.99,
    category: 'T-Shirts',
    subcategory: 'Striped Tees',
    images: [
      'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800',
      'https://images.unsplash.com/photo-1627225924765-552d49cf47ad?w=800',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy/White', 'Black/White', 'Red/White'],
    materials: ['Cotton Jersey'],
    stock: 82,
    rating: 4.6,
    reviewCount: 143,
    featured: true,
    newArrival: false,
    bestseller: true,
    tags: ['striped', 't-shirt', 'classic'],
    sku: 'TS-004'
  },
  {
    id: '5',
    name: 'Oversized T-Shirt',
    slug: 'oversized-tshirt',
    description: 'Trendy oversized fit t-shirt. Relaxed and comfortable with a modern silhouette.',
    price: 38.99,
    salePrice: 31.99,
    category: 'T-Shirts',
    subcategory: 'Oversized Tees',
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800',
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Beige', 'Black', 'White', 'Green'],
    materials: ['Heavy Cotton'],
    stock: 120,
    rating: 4.7,
    reviewCount: 201,
    featured: false,
    newArrival: true,
    bestseller: true,
    tags: ['oversized', 't-shirt', 'streetwear'],
    sku: 'TS-005'
  },
  {
    id: '6',
    name: 'Pocket T-Shirt',
    slug: 'pocket-tshirt',
    description: 'Classic pocket tee with a modern twist. Comfortable and versatile for any occasion.',
    price: 30.99,
    category: 'T-Shirts',
    subcategory: 'Pocket Tees',
    images: [
      'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=800',
      'https://images.unsplash.com/photo-1622445275854-022697c5f936?w=800',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy', 'Forest Green', 'Burgundy', 'Black'],
    materials: ['Cotton'],
    stock: 105,
    rating: 4.5,
    reviewCount: 167,
    featured: true,
    newArrival: false,
    bestseller: false,
    tags: ['pocket', 't-shirt', 'casual'],
    sku: 'TS-006'
  },

  // Hoodies
  {
    id: '7',
    name: 'Classic Pullover Hoodie',
    slug: 'classic-pullover-hoodie',
    description: 'Essential pullover hoodie with kangaroo pocket. Soft fleece interior for maximum warmth.',
    price: 59.99,
    salePrice: 49.99,
    category: 'Hoodies',
    subcategory: 'Pullover',
    images: [
      'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800',
      'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Gray', 'Navy', 'Olive'],
    materials: ['Cotton Fleece Blend'],
    stock: 88,
    rating: 4.9,
    reviewCount: 312,
    featured: true,
    newArrival: false,
    bestseller: true,
    tags: ['hoodie', 'pullover', 'fleece'],
    sku: 'HD-001'
  },
  {
    id: '8',
    name: 'Zip-Up Hoodie',
    slug: 'zip-up-hoodie',
    description: 'Versatile full-zip hoodie. Perfect for layering with a comfortable relaxed fit.',
    price: 64.99,
    category: 'Hoodies',
    subcategory: 'Zip-Up',
    images: [
      'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800',
      'https://images.unsplash.com/photo-1620799139507-2a76f79a2f4d?w=800',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Charcoal', 'Black', 'Navy', 'Burgundy'],
    materials: ['Cotton Polyester Blend'],
    stock: 76,
    rating: 4.7,
    reviewCount: 245,
    featured: true,
    newArrival: true,
    bestseller: false,
    tags: ['hoodie', 'zip-up', 'layering'],
    sku: 'HD-002'
  },
  {
    id: '9',
    name: 'Oversized Hoodie',
    slug: 'oversized-hoodie',
    description: 'Trendy oversized hoodie with dropped shoulders. Ultimate comfort meets street style.',
    price: 69.99,
    salePrice: 54.99,
    category: 'Hoodies',
    subcategory: 'Oversized',
    images: [
      'https://images.unsplash.com/photo-1614676471928-2ed0ad1061a4?w=800',
      'https://images.unsplash.com/photo-1618677366787-2d0b75d3ad77?w=800',
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Sand', 'Black', 'White', 'Sage'],
    materials: ['Heavy Cotton Fleece'],
    stock: 92,
    rating: 4.8,
    reviewCount: 278,
    featured: false,
    newArrival: true,
    bestseller: true,
    tags: ['oversized', 'hoodie', 'streetwear'],
    sku: 'HD-003'
  },
  {
    id: '10',
    name: 'Tech Fleece Hoodie',
    slug: 'tech-fleece-hoodie',
    description: 'Innovative tech fleece hoodie. Lightweight, warm, and incredibly soft.',
    price: 79.99,
    category: 'Hoodies',
    subcategory: 'Tech Fleece',
    images: [
      'https://images.unsplash.com/photo-1620799140188-3b2a02fd9a77?w=800',
      'https://images.unsplash.com/photo-1620799139834-6b8f844fbe61?w=800',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Gray'],
    materials: ['Tech Fleece'],
    stock: 64,
    rating: 4.9,
    reviewCount: 189,
    featured: true,
    newArrival: true,
    bestseller: false,
    tags: ['tech', 'hoodie', 'performance'],
    sku: 'HD-004'
  },
  {
    id: '11',
    name: 'Graphic Hoodie',
    slug: 'graphic-hoodie',
    description: 'Bold graphic print hoodie. Make a statement with comfortable style.',
    price: 62.99,
    category: 'Hoodies',
    subcategory: 'Graphic',
    images: [
      'https://images.unsplash.com/photo-1509942774463-acf339c70d44?w=800',
      'https://images.unsplash.com/photo-1620799140397-f737e2c6e1fd?w=800',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Maroon'],
    materials: ['Cotton Blend'],
    stock: 58,
    rating: 4.6,
    reviewCount: 198,
    featured: false,
    newArrival: false,
    bestseller: true,
    tags: ['graphic', 'hoodie', 'trendy'],
    sku: 'HD-005'
  },
  {
    id: '12',
    name: 'Lightweight Hoodie',
    slug: 'lightweight-hoodie',
    description: 'Perfect for layering or mild weather. Soft, breathable, and comfortable.',
    price: 54.99,
    salePrice: 44.99,
    category: 'Hoodies',
    subcategory: 'Lightweight',
    images: [
      'https://images.unsplash.com/photo-1620799140195-e1f4d6c5e8b5?w=800',
      'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Heather Gray', 'Navy', 'Olive', 'Black'],
    materials: ['Cotton Jersey'],
    stock: 110,
    rating: 4.5,
    reviewCount: 156,
    featured: true,
    newArrival: false,
    bestseller: false,
    tags: ['lightweight', 'hoodie', 'layering'],
    sku: 'HD-006'
  },
];

export const mockOrders: Order[] = [];
export const mockReviews: Review[] = [];
export const mockCoupons: Coupon[] = [];