// Wishlist page demo data with images

export const wishlistItems = [
  {
    id: 'wish-1',
    productId: 'prod-1',
    name: 'Classic Black T-Shirt',
    category: 'Shirts',
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    image: 'https://images.unsplash.com/photo-1516082669438-2d2bb5082626?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwdHNoaXJ0fGVufDF8fHx8MTc2MjQxNDMzMHww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.5,
    reviews: 234,
    inStock: true,
    stockLevel: 'high',
    addedDate: '2025-10-15',
    priceDropped: true,
    priceDropAmount: 10.00,
  },
  {
    id: 'wish-2',
    productId: 'prod-2',
    name: 'Premium Denim Jeans',
    category: 'Pants',
    price: 119.99,
    originalPrice: null,
    discount: 0,
    image: 'https://images.unsplash.com/photo-1714143136372-ddaf8b606da7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwZGVuaW0lMjBqZWFuc3xlbnwxfHx8fDE3NjIzMTczNjh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.8,
    reviews: 156,
    inStock: true,
    stockLevel: 'medium',
    addedDate: '2025-10-20',
    priceDropped: false,
    priceDropAmount: 0,
  },
  {
    id: 'wish-3',
    productId: 'prod-3',
    name: 'Leather Chelsea Boots',
    category: 'Shoes',
    price: 189.99,
    originalPrice: 249.99,
    discount: 24,
    image: 'https://images.unsplash.com/photo-1585557488780-78b585ba3117?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwYm9vdHN8ZW58MXx8fHwxNzYyNDE0MzMyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.7,
    reviews: 89,
    inStock: true,
    stockLevel: 'low',
    addedDate: '2025-11-01',
    priceDropped: true,
    priceDropAmount: 60.00,
  },
  {
    id: 'wish-4',
    productId: 'prod-4',
    name: 'Wool Blazer',
    category: 'Jackets',
    price: 299.99,
    originalPrice: null,
    discount: 0,
    image: 'https://images.unsplash.com/photo-1598915850252-fb07ad1e6768?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwYmxhemVyfGVufDF8fHx8MTc2MjM2NTc4NHww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.9,
    reviews: 45,
    inStock: true,
    stockLevel: 'low',
    addedDate: '2025-09-25',
    priceDropped: false,
    priceDropAmount: 0,
  },
  {
    id: 'wish-5',
    productId: 'prod-5',
    name: 'Leather Wallet',
    category: 'Accessories',
    price: 79.99,
    originalPrice: 99.99,
    discount: 20,
    image: 'https://images.unsplash.com/photo-1675582122314-cabef1d757ec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwd2FsbGV0fGVufDF8fHx8MTc2MjQxNDMzM3ww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.6,
    reviews: 312,
    inStock: true,
    stockLevel: 'high',
    addedDate: '2025-11-03',
    priceDropped: true,
    priceDropAmount: 20.00,
  },
  {
    id: 'wish-6',
    productId: 'prod-6',
    name: 'White Sneakers',
    category: 'Shoes',
    price: 149.99,
    originalPrice: null,
    discount: 0,
    image: 'https://images.unsplash.com/photo-1672622012959-45355279c93e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwc25lYWtlcnN8ZW58MXx8fHwxNzYyNDE0MzMxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.8,
    reviews: 201,
    inStock: true,
    stockLevel: 'medium',
    addedDate: '2025-10-28',
    priceDropped: false,
    priceDropAmount: 0,
  },
  {
    id: 'wish-7',
    productId: 'prod-7',
    name: 'Grey Hoodie',
    category: 'Jackets',
    price: 89.99,
    originalPrice: 109.99,
    discount: 18,
    image: 'https://images.unsplash.com/photo-1688111421205-a0a85415b224?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwaG9vZGllfGVufDF8fHx8MTc2MjQxNDMzMnww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.4,
    reviews: 167,
    inStock: false,
    stockLevel: 'out',
    addedDate: '2025-10-05',
    priceDropped: true,
    priceDropAmount: 20.00,
  },
  {
    id: 'wish-8',
    productId: 'prod-8',
    name: 'Casual Baseball Cap',
    category: 'Accessories',
    price: 34.99,
    originalPrice: null,
    discount: 0,
    image: 'https://images.unsplash.com/photo-1558466124-a150281f04cb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwY2FwfGVufDF8fHx8MTc2MjQxNDMzM3ww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.3,
    reviews: 423,
    inStock: true,
    stockLevel: 'high',
    addedDate: '2025-11-05',
    priceDropped: false,
    priceDropAmount: 0,
  },
];

export const wishlistCollections = [
  {
    id: 'all',
    name: 'All Items',
    count: 8,
    icon: '📦',
  },
  {
    id: 'winter',
    name: 'Winter Collection',
    count: 3,
    icon: '❄️',
  },
  {
    id: 'formal',
    name: 'Formal Wear',
    count: 2,
    icon: '👔',
  },
  {
    id: 'casual',
    name: 'Casual Style',
    count: 3,
    icon: '👕',
  },
];

export const wishlistStats = {
  totalItems: 8,
  totalValue: 994.92,
  potentialSavings: 110.00,
  priceDropAlerts: 4,
};

export const priceAlerts = [
  {
    id: 'alert-1',
    productId: 'prod-1',
    productName: 'Classic Black T-Shirt',
    oldPrice: 39.99,
    newPrice: 29.99,
    dropAmount: 10.00,
    dropPercentage: 25,
    date: '2025-11-04',
  },
  {
    id: 'alert-2',
    productId: 'prod-3',
    productName: 'Leather Chelsea Boots',
    oldPrice: 249.99,
    newPrice: 189.99,
    dropAmount: 60.00,
    dropPercentage: 24,
    date: '2025-11-02',
  },
  {
    id: 'alert-3',
    productId: 'prod-5',
    productName: 'Leather Wallet',
    oldPrice: 99.99,
    newPrice: 79.99,
    dropAmount: 20.00,
    dropPercentage: 20,
    date: '2025-11-03',
  },
  {
    id: 'alert-4',
    productId: 'prod-7',
    productName: 'Grey Hoodie',
    oldPrice: 109.99,
    newPrice: 89.99,
    dropAmount: 20.00,
    dropPercentage: 18,
    date: '2025-11-01',
  },
];

export const stockAlerts = [
  {
    id: 'stock-1',
    productId: 'prod-3',
    productName: 'Leather Chelsea Boots',
    stockLevel: 'low',
    message: 'Only 3 left in stock!',
    urgency: 'high',
  },
  {
    id: 'stock-2',
    productId: 'prod-4',
    productName: 'Wool Blazer',
    stockLevel: 'low',
    message: 'Limited stock available',
    urgency: 'medium',
  },
  {
    id: 'stock-3',
    productId: 'prod-7',
    productName: 'Grey Hoodie',
    stockLevel: 'out',
    message: 'Back in stock soon',
    urgency: 'info',
  },
];

export const recommendedProducts = [
  {
    id: 'rec-1',
    name: 'Formal Suit',
    category: 'Jackets',
    price: 499.99,
    image: 'https://images.unsplash.com/photo-1679101893310-9b9adb4b733b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwc3VpdHxlbnwxfHx8fDE3NjI0MTQxMDR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.9,
    reason: 'Pairs well with your Wool Blazer',
  },
  {
    id: 'rec-2',
    name: 'Leather Belt',
    category: 'Accessories',
    price: 59.99,
    image: 'https://images.unsplash.com/photo-1684510334550-0c4fa8aaffd1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwYmVsdHxlbnwxfHx8fDE3NjI0MTQzMzN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.5,
    reason: 'Completes your outfit',
  },
  {
    id: 'rec-3',
    name: 'Aviator Sunglasses',
    category: 'Accessories',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1708702101923-f06afcb4e2b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwc3VuZ2xhc3Nlc3xlbnwxfHx8fDE3NjI0MTQxMDR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.7,
    reason: 'Trending accessory',
  },
  {
    id: 'rec-4',
    name: 'Luxury Watch',
    category: 'Accessories',
    price: 899.99,
    image: 'https://images.unsplash.com/photo-1751437797070-54ac95740dac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwbHV4dXJ5JTIwd2F0Y2h8ZW58MXx8fHwxNzYyNDE0MTAzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 5.0,
    reason: 'Premium choice for you',
  },
];

export const wishlistActions = [
  {
    id: 'share',
    label: 'Share Wishlist',
    icon: '🔗',
    description: 'Share your wishlist with friends and family',
  },
  {
    id: 'print',
    label: 'Print Wishlist',
    icon: '🖨️',
    description: 'Print your wishlist for offline reference',
  },
  {
    id: 'create-collection',
    label: 'Create Collection',
    icon: '📁',
    description: 'Organize items into collections',
  },
  {
    id: 'price-alerts',
    label: 'Manage Alerts',
    icon: '🔔',
    description: 'Set up price drop notifications',
  },
];

export const emptyWishlistMessages = {
  title: 'Your wishlist is empty',
  message: 'Start adding items you love to keep track of them!',
  suggestions: [
    'Browse our latest collections',
    'Check out bestsellers',
    'Explore sale items',
  ],
};
