// Search page demo data with images

export const searchSuggestions = [
  'Black leather jacket',
  'White sneakers',
  'Slim fit jeans',
  'Casual t-shirts',
  'Winter coats',
  'Running shoes',
  'Formal shirts',
  'Denim jackets',
];

export const popularSearches = [
  { term: 'Jackets', count: 1234 },
  { term: 'Shoes', count: 987 },
  { term: 'T-shirts', count: 856 },
  { term: 'Jeans', count: 743 },
  { term: 'Accessories', count: 621 },
];

export const searchFilters = {
  categories: [
    { id: 'jackets', name: 'Jackets', count: 45 },
    { id: 'shirts', name: 'Shirts', count: 67 },
    { id: 'pants', name: 'Pants', count: 52 },
    { id: 'shoes', name: 'Shoes', count: 38 },
    { id: 'accessories', name: 'Accessories', count: 29 },
  ],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: [
    { id: 'black', name: 'Black', hex: '#000000' },
    { id: 'white', name: 'White', hex: '#FFFFFF' },
    { id: 'navy', name: 'Navy', hex: '#000080' },
    { id: 'grey', name: 'Grey', hex: '#808080' },
    { id: 'blue', name: 'Blue', hex: '#0000FF' },
    { id: 'red', name: 'Red', hex: '#FF0000' },
  ],
  priceRanges: [
    { id: 'under-50', label: 'Under $50', min: 0, max: 50 },
    { id: '50-100', label: '$50 - $100', min: 50, max: 100 },
    { id: '100-200', label: '$100 - $200', min: 100, max: 200 },
    { id: '200-500', label: '$200 - $500', min: 200, max: 500 },
    { id: 'over-500', label: 'Over $500', min: 500, max: Infinity },
  ],
};

export const searchResults = [
  {
    id: 'search-1',
    name: 'Classic Black T-Shirt',
    category: 'Shirts',
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    image: 'https://images.unsplash.com/photo-1516082669438-2d2bb5082626?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwdHNoaXJ0fGVufDF8fHx8MTc2MjQxNDMzMHww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.5,
    reviews: 234,
    badge: 'SALE',
    inStock: true,
    colors: ['Black', 'White', 'Grey'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'search-2',
    name: 'Premium Denim Jeans',
    category: 'Pants',
    price: 119.99,
    originalPrice: null,
    discount: 0,
    image: 'https://images.unsplash.com/photo-1714143136372-ddaf8b606da7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwZGVuaW0lMjBqZWFuc3xlbnwxfHx8fDE3NjIzMTczNjh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.8,
    reviews: 156,
    badge: 'NEW',
    inStock: true,
    colors: ['Blue', 'Black'],
    sizes: ['28', '30', '32', '34', '36'],
  },
  {
    id: 'search-3',
    name: 'Leather Chelsea Boots',
    category: 'Shoes',
    price: 189.99,
    originalPrice: 249.99,
    discount: 24,
    image: 'https://images.unsplash.com/photo-1585557488780-78b585ba3117?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwYm9vdHN8ZW58MXx8fHwxNzYyNDE0MzMyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.7,
    reviews: 89,
    badge: 'SALE',
    inStock: true,
    colors: ['Brown', 'Black'],
    sizes: ['7', '8', '9', '10', '11'],
  },
  {
    id: 'search-4',
    name: 'Wool Blazer',
    category: 'Jackets',
    price: 299.99,
    originalPrice: null,
    discount: 0,
    image: 'https://images.unsplash.com/photo-1598915850252-fb07ad1e6768?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwYmxhemVyfGVufDF8fHx8MTc2MjM2NTc4NHww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.9,
    reviews: 45,
    badge: 'PREMIUM',
    inStock: true,
    colors: ['Navy', 'Grey', 'Black'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'search-5',
    name: 'Leather Wallet',
    category: 'Accessories',
    price: 79.99,
    originalPrice: 99.99,
    discount: 20,
    image: 'https://images.unsplash.com/photo-1675582122314-cabef1d757ec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwd2FsbGV0fGVufDF8fHx8MTc2MjQxNDMzM3ww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.6,
    reviews: 312,
    badge: 'SALE',
    inStock: true,
    colors: ['Brown', 'Black', 'Tan'],
    sizes: ['One Size'],
  },
  {
    id: 'search-6',
    name: 'White Sneakers',
    category: 'Shoes',
    price: 149.99,
    originalPrice: null,
    discount: 0,
    image: 'https://images.unsplash.com/photo-1672622012959-45355279c93e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwc25lYWtlcnN8ZW58MXx8fHwxNzYyNDE0MzMxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.8,
    reviews: 201,
    badge: 'POPULAR',
    inStock: true,
    colors: ['White', 'Black', 'Grey'],
    sizes: ['7', '8', '9', '10', '11', '12'],
  },
  {
    id: 'search-7',
    name: 'Grey Hoodie',
    category: 'Jackets',
    price: 89.99,
    originalPrice: 109.99,
    discount: 18,
    image: 'https://images.unsplash.com/photo-1688111421205-a0a85415b224?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwaG9vZGllfGVufDF8fHx8MTc2MjQxNDMzMnww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.4,
    reviews: 167,
    badge: 'SALE',
    inStock: false,
    colors: ['Grey', 'Black', 'Navy'],
    sizes: ['M', 'L', 'XL'],
  },
  {
    id: 'search-8',
    name: 'Casual Baseball Cap',
    category: 'Accessories',
    price: 34.99,
    originalPrice: null,
    discount: 0,
    image: 'https://images.unsplash.com/photo-1558466124-a150281f04cb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwY2FwfGVufDF8fHx8MTc2MjQxNDMzM3ww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.3,
    reviews: 423,
    badge: 'BESTSELLER',
    inStock: true,
    colors: ['Black', 'Navy', 'Khaki', 'White'],
    sizes: ['One Size'],
  },
  {
    id: 'search-9',
    name: 'Formal Suit',
    category: 'Jackets',
    price: 499.99,
    originalPrice: 649.99,
    discount: 23,
    image: 'https://images.unsplash.com/photo-1679101893310-9b9adb4b733b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwc3VpdHxlbnwxfHx8fDE3NjI0MTQxMDR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.9,
    reviews: 78,
    badge: 'SALE',
    inStock: true,
    colors: ['Navy', 'Charcoal', 'Black'],
    sizes: ['38', '40', '42', '44', '46'],
  },
  {
    id: 'search-10',
    name: 'Luxury Watch',
    category: 'Accessories',
    price: 899.99,
    originalPrice: null,
    discount: 0,
    image: 'https://images.unsplash.com/photo-1751437797070-54ac95740dac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwbHV4dXJ5JTIwd2F0Y2h8ZW58MXx8fHwxNzYyNDE0MTAzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 5.0,
    reviews: 34,
    badge: 'LUXURY',
    inStock: true,
    colors: ['Silver', 'Gold', 'Black'],
    sizes: ['One Size'],
  },
  {
    id: 'search-11',
    name: 'Leather Belt',
    category: 'Accessories',
    price: 59.99,
    originalPrice: 79.99,
    discount: 25,
    image: 'https://images.unsplash.com/photo-1684510334550-0c4fa8aaffd1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwYmVsdHxlbnwxfHx8fDE3NjI0MTQzMzN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.5,
    reviews: 189,
    badge: 'SALE',
    inStock: true,
    colors: ['Brown', 'Black'],
    sizes: ['32', '34', '36', '38', '40'],
  },
  {
    id: 'search-12',
    name: 'Aviator Sunglasses',
    category: 'Accessories',
    price: 129.99,
    originalPrice: null,
    discount: 0,
    image: 'https://images.unsplash.com/photo-1708702101923-f06afcb4e2b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZW5zJTIwc3VuZ2xhc3Nlc3xlbnwxfHx8fDE3NjI0MTQxMDR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.7,
    reviews: 145,
    badge: 'TRENDING',
    inStock: true,
    colors: ['Gold', 'Silver', 'Black'],
    sizes: ['One Size'],
  },
];

export const trendingSearches = [
  { term: 'Winter jackets', trend: 'up', change: 45 },
  { term: 'Formal wear', trend: 'up', change: 32 },
  { term: 'Sneakers', trend: 'up', change: 28 },
  { term: 'Hoodies', trend: 'down', change: -12 },
  { term: 'Accessories', trend: 'up', change: 18 },
];

export const recentSearches = [
  'Black leather jacket',
  'White sneakers',
  'Denim jeans',
  'Formal shirts',
];

export const sortOptions = [
  { value: 'relevance', label: 'Most Relevant' },
  { value: 'price-low', label: 'Price: Low to High' },
  { value: 'price-high', label: 'Price: High to Low' },
  { value: 'newest', label: 'Newest Arrivals' },
  { value: 'rating', label: 'Highest Rated' },
  { value: 'popular', label: 'Most Popular' },
];

export const quickFilters = [
  { id: 'sale', label: 'On Sale', icon: '🏷️' },
  { id: 'new', label: 'New Arrivals', icon: '✨' },
  { id: 'popular', label: 'Popular', icon: '🔥' },
  { id: 'premium', label: 'Premium', icon: '⭐' },
  { id: 'free-shipping', label: 'Free Shipping', icon: '🚚' },
];
